# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrader', '0002_auto_20171113_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktrader.Employee')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktrader.Task')),
            ],
        ),
    ]
