# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrader', '0003_random_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='tasktrader.Company'),
            preserve_default=False,
        ),
    ]
