# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrader', '0004_location_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='company',
        ),
    ]
