# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrader', '0010_auto_20171203_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campus_name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tasktrader.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tasktrader.Location'),
            preserve_default=False,
        ),
    ]
