# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrader', '0013_auto_20171203_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='company_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='tasktrader.Company'),
        ),
    ]
