# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasktrader.Employee')),
            ],
        ),
    ]
