# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrader', '0002_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_commitment',
            field=models.FloatField(default=0, null=True),
        ),
    ]
