# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrader', '0005_auto_20171204_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_commitment',
        ),
    ]
