# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktrader', '0006_auto_20171204_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_commitment',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
